### ISSUE TITLE
Conflict with plugin redmine_dmsf ?

### ISSUE THREAD

**Issue by dnyamy** [paginagmbh/redmine_project_alias_2#6]
Hello,
I am struggling to make this plugin work with my 3.4 Redmine.
Clicking on the admin page to configure the plugin yields following error in log file :

```
Started GET "/project_aliases" for 80.215.68.58 at 2019-10-21 12:55:01 +0200

ActionController::RoutingError (uninitialized constant ProjectAliasesController):
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in call'
```

Worst I cannot even open projects any more : 
```
Started GET "/projects/modele-essais?jump=admin" for 80.215.68.58 at 2019-10-21 12:55:55 +0200
Processing by ProjectsController#show as HTML
  Parameters: {"jump"=>"admin", "id"=>"modele-essais"}
  Current user: dnyamy (id=5)
Completed 500 Internal Server Error in 20ms (ActiveRecord: 11.0ms)

NameError (uninitialized constant AliasProjectPatch::ClassMethods::ProjectAlias):
  plugins/redmine_project_alias_2-redmine-2.6-3.x/lib/alias_project_patch.rb:19:in `find_by_identifier'
  app/models/project.rb:308:in `find'
  app/controllers/application_controller.rb:276:in `find_project'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in call'
```

Seems the is a conflict with another plugin which is installed : redmine_dmsf

Please can any body help ?

Thanks, and regards

Dorice

**Comment by tofi86** [comment]
I cannot Test this at the moment but I spotted something in your logs:


plugins/redmine_project_alias_2-redmine-2.6-3.x/

Is this the path where you installed the plugin? Then it must be named after the plugin identifier as described in the readme:


plugins/redmine_project_alias_2/

Can you rename the folder and re-install the plugin as described in the readme and try if it works?

**Comment by dnyamy** [comment]
Oooh !!!
I had totally forgotten the instruction
I have just renamed the folder, and it works !!!
Thank you very much 
dn
